In [1]:
import pandas as pd
import numpy as np

In [15]:
df = pd.read_csv('../data/facebook_combined.txt', sep=' ', names=['first_node', 'last_node'])
df = df.head(2000)

In [11]:
df.shape

(2000, 2)

In [12]:
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1995    False
1996    False
1997    False
1998    False
1999    False
Length: 2000, dtype: bool

In [16]:
df.drop_duplicates(inplace=True)
df.shape

(2000, 2)

In [14]:
data = {
  "first_node": [420, 380, 390],
  "last_node": [420, 40, 45]
}

df2 = pd.DataFrame(data)
df2.head()

   first_node  last_node
0         420        420
1         380         40
2         390         45

In [9]:
df3 = df2.apply(lambda x: df.drop(x) if x['first_node'] == x['last_node'] else x, axis=1)
df3.head()

0          first_node  last_node
0              0  ...
1    first_node    380
last_node      40
Name: 1, d...
2    first_node    390
last_node      45
Name: 2, d...
dtype: object

In [20]:
df4 = df[df['first_node'] != df['last_node']]
df4.shape

(2000, 2)

In [36]:
df5 = df[df['first_node'] != df['last_node']]
df5

       first_node  last_node
0               0          1
1               0          2
2               0          3
3               0          4
4               0          5
...           ...        ...
88229        4026       4030
88230        4027       4031
88231        4027       4032
88232        4027       4038
88233        4031       4038

[88234 rows x 2 columns]