In [17]:
import networkx as nx
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../data/bug_groupby.csv')
df.head()

,Unnamed: 0,node,community,degree,intra,inter,local_closeness,global_closeness,local_core_num,global_core_num,betweenness,eigenvector,trussness
0,0,0,c0,0.487360,159,188,1.000000,0.661096,6,11,0.704019,0.441813,4
1,1,1,c3,0.023876,12,5,0.555556,0.401806,6,9,0.000119,0.043738,5
2,2,2,c0,0.014045,10,0,0.516234,0.400225,6,6,0.000026,0.022376,4
3,3,3,c5,0.023876,15,2,0.502415,0.401806,9,10,0.000079,0.071224,8
4,4,4,c0,0.014045,10,0,0.516234,0.400225,3,3,0.000043,0.021136,4

In [5]:
local_thresholds = df.groupby('community')
local_thresholds.head()

,Unnamed: 0,node,community,degree,intra,inter,local_closeness,global_closeness,local_core_num,global_core_num,betweenness,eigenvector,trussness
0,0,0,c0,0.487360,159,188,1.000000,0.661096,6,11,0.704019,0.441813,4
1,1,1,c3,0.023876,12,5,0.555556,0.401806,6,9,0.000119,0.043738,5
2,2,2,c0,0.014045,10,0,0.516234,0.400225,6,6,0.000026,0.022376,4
3,3,3,c5,0.023876,15,2,0.502415,0.401806,9,10,0.000079,0.071224,8
4,4,4,c0,0.014045,10,0,0.516234,0.400225,3,3,0.000043,0.021136,4
5,5,5,c3,0.018258,7,6,0.394737,0.400901,4,8,0.000096,0.033900,3
6,6,6,c0,0.008427,6,0,0.509615,0.399327,4,4,0.000005,0.018874,5
7,7,7,c4,0.028090,12,8,0.628571,0.402487,4,9,0.000212,0.045689,4
8,8,8,c0,0.011236,8,0,0.512903,0.399775,3,3,0.000020,0.019976,4
9,9,9,c5,0.080056,53,4,0.654088,0.411085,10,11,0.001157,0.169958,6
10,10,10,c5,0.014045,9,1,0.456140,0.400225,8,9,0.000014,0.045349,4
13,13,13,c5,0.043539,29,2,0.574586,0.405006,10,11,0.000213,0.111758,8
16,16,16,c5,0.012640,7,2,0.401544,0.400000,6,8,0.000021,0.032352,3
22,22,22,c4,0.015449,7,4,0.448980,0.400450,4,7,0.000055,0.030461,4
24,24,24,c3,0.022472,15,1,0.523256,0.401579,6,9,0.000028,0.032623,9
27,27,27,c3,0.007022,2,3,0.330882,0.399103,2,4,0.000006,0.021785,4
30,30,30,c3,0.023876,7,10,0.424528,0.401806,3,9,0.000105,0.059296,5
31,31,31,c4,0.032303,10,13,0.523810,0.403171,4,10,0.000248,0.073461,4
34,34,34,c1,0.007022,4,1,0.336142,0.399775,2,2,0.002048,0.016408,2
38,38,38,c4,0.012640,4,5,0.468085,0.400000,2,6,0.000040,0.029521,4
51,51,51,c4,0.009831,4,3,0.366667,0.399551,4,6,0.000003,0.029629,8
58,58,58,c2,0.016854,10,2,0.580645,0.504249,2,3,0.023068,0.018139,2
64,64,64,c2,0.009831,5,2,0.428571,0.399551,2,3,0.000018,0.021983,4
81,81,81,c2,0.004213,2,1,0.375000,0.398656,1,2,0.000002,0.016806,3
100,100,100,c2,0.012640,6,3,0.461538,0.400000,2,3,0.000042,0.025038,3
107,107,107,c1,0.505618,357,3,0.991713,0.669173,2,3,0.749694,0.030637,2
150,150,150,c2,0.004213,2,1,0.333333,0.398656,2,3,0.000000,0.017269,4
173,173,173,c1,0.004213,1,2,0.251753,0.399327,1,2,0.000006,0.017659,3
348,348,348,c1,0.002809,2,0,0.501397,0.401806,2,2,0.000351,0.001664,2
349,349,414,c1,0.002809,2,0,0.501397,0.401806,2,2,0.000351,0.001664,2

In [10]:
local_thresholds = df.groupby('community').count()
local_thresholds.head(5)

,Unnamed: 0,node,degree,intra,inter,local_closeness,global_closeness,local_core_num,global_core_num,betweenness,eigenvector,trussness
community,,,,,,,,,,,,
c0,160,160,160,160,160,160,160,160,160,160,160,160
c1,360,360,360,360,360,360,360,360,360,360,360,360
c2,19,19,19,19,19,19,19,19,19,19,19,19
c3,46,46,46,46,46,46,46,46,46,46,46,46
c4,23,23,23,23,23,23,23,23,23,23,23,23

In [12]:
percentiles = [0.25, 0.50, 0.75, 0.90]

local_thresholds = df.groupby('community').quantile(percentiles, interpolation='nearest')
local_thresholds.head(5)

                Unnamed: 0  node    degree  intra  inter  local_closeness  \
community
c0        0.25          95    95  0.001404      1      0         0.501577
          0.50         179   179  0.004213      2      0         0.503165
          0.75         250   250  0.007022      5      0         0.507987
          0.90         301   301  0.011236      8      1         0.512903
c1        0.25         443   957  0.001404      1      0         0.498611

                global_closeness  local_core_num  global_core_num  \
community
c0        0.25          0.398210               1                1
          0.50          0.398656               2                3
          0.75          0.399103               4                4
          0.90          0.399775               5                6
c1        0.25          0.401127               1                1

                betweenness  eigenvector  trussness
community
c0        0.25     0.000000     0.015607          2
          0.50     0.000000     0.017061          3
          0.75     0.000003     0.020025          4
          0.90     0.000020     0.023037          5
c1        0.25     0.000000     0.001084          2

In [13]:
local_df = df[['intra', 'inter', 'local_closeness', 'local_core_num', 'betweenness']]
local_df.head()

   intra  inter  local_closeness  local_core_num  betweenness
0    159    188         1.000000               6     0.704019
1     12      5         0.555556               6     0.000119
2     10      0         0.516234               6     0.000026
3     15      2         0.502415               9     0.000079
4     10      0         0.516234               3     0.000043

In [24]:
G = nx.binomial_graph(n=10, p=0.5)
result = nx.degree_centrality(G)

In [28]:
if set(G.nodes()) == set(result.keys()):
    print(True)

True

In [34]:
G = nx.Graph()
G.add_node(1)
result = nx.degree_centrality(G)

if list(result.keys()) == [1]:
    print(True)
else:
    print(False)

True

In [35]:
result[1]

1

In [36]:
e_result = nx.eigenvector_centrality(G)
e_result[1]

1.0

Neither degree or eigenvector centrality should return 1 or 1.0 as there is only 1 node.

In [43]:
print(e_result.values())

dict_values([1.0])

In [44]:
k_result = nx.k_truss(G)
print(k_result)

TypeError: k_truss() missing 1 required positional argument: 'k'

Error states missing arguments. <br>
After viewing the k_truss method documentation, it says that the Graph must have at least 3 vertices(nodes).<br>
I will add a check at the top of the function to check that the graph has at least 3+ nodes, if not it will return {node: 0}

In [54]:
list(G.nodes)[0]

1

In [81]:
G = nx.Graph()
G.add_node(1)
G.nodes()

NodeView((1,))

In [82]:
deg = nx.degree_centrality(G)
deg[1]

1

In [83]:
e = nx.eigenvector_centrality(G)
e

{1: 1.0}

In [70]:
G.number_of_edges()

0