In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../data/facebook_combined.txt', sep=' ', names=['first_node', 'last_node'])
df.head()

   first_node  last_node
0           0          1
1           0          2
2           0          3
3           0          4
4           0          5

In [8]:
df['empty'] = [np.empty(0,dtype=str)]*len(df)

In [10]:
df.head()

   first_node  last_node empty
0           0          1    []
1           0          2    []
2           0          3    []
3           0          4    []
4           0          5    []

In [23]:
df.loc[0, 'empty'] += 'sup'
df.head()

   first_node  last_node   empty    2    1
0           0          1  spusup  sup  sup
1           0          2      []  NaN  NaN
2           0          3      []  NaN  NaN
3           0          4      []  NaN  NaN
4           0          5      []  NaN  NaN