In [27]:
import pandas as pd
import numpy as np
import networkx as nx

In [2]:
df = pd.read_csv('../data/raw/facebook_combined.txt', sep=' ', names=['first_node', 'last_node'])
df.head()

   first_node  last_node
0           0          1
1           0          2
2           0          3
3           0          4
4           0          5

In [4]:
G = nx.Graph()
G.add_edges_from(df.values)

In [8]:
df['empty'] = [np.empty(0,dtype=str)]*len(df)

In [10]:
df.head()

   first_node  last_node empty
0           0          1    []
1           0          2    []
2           0          3    []
3           0          4    []
4           0          5    []

In [23]:
df.loc[0, 'empty'] += 'sup'
df.head()

   first_node  last_node   empty    2    1
0           0          1  spusup  sup  sup
1           0          2      []  NaN  NaN
2           0          3      []  NaN  NaN
3           0          4      []  NaN  NaN
4           0          5      []  NaN  NaN

In [20]:
coms_list = nx.community.louvain_communities(G)
node_coms = {}

for index, com in enumerate(coms_list):
    for n in com:
        node_coms[n] = f'c{index}'

comms_dict = {}
for index, com in enumerate(coms_list):
    comms_dict[f'c{index}'] = list(com)

print(comms_dict)

{'c0': [np.int64(0), np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12), np.int64(13), np.int64(14), np.int64(15), np.int64(16), np.int64(17), np.int64(18), np.int64(19), np.int64(20), np.int64(21), np.int64(22), np.int64(23), np.int64(24), np.int64(25), np.int64(26), np.int64(27), np.int64(28), np.int64(29), np.int64(30), np.int64(31), np.int64(32), np.int64(33), np.int64(35), np.int64(36), np.int64(37), np.int64(38), np.int64(39), np.int64(40), np.int64(41), np.int64(42), np.int64(43), np.int64(44), np.int64(45), np.int64(46), np.int64(47), np.int64(48), np.int64(49), np.int64(50), np.int64(51), np.int64(52), np.int64(53), np.int64(54), np.int64(55), np.int64(56), np.int64(57), np.int64(58), np.int64(59), np.int64(60), np.int64(61), np.int64(62), np.int64(63), np.int64(64), np.int64(65), np.int64(66), np.int64(67), np.int64(68), np.int64(69), np.int64(70), np.int64(71), np.int64(72), np.int64(73), np.int64(74), np.int64(75), np.int64(76), np.int64(77), np.int64(78), np.int64(79), np.int64(80), np.int64(81), np.int64(82), np.int64(83), np.int64(84), np.int64(85), np.int64(86), np.int64(87), np.int64(88), np.int64(89), np.int64(90), np.int64(91), np.int64(92), np.int64(93), np.int64(94), np.int64(95), np.int64(96), np.int64(97), np.int64(98), np.int64(99), np.int64(100), np.int64(101), np.int64(102), np.int64(103), np.int64(104), np.int64(105), np.int64(106), np.int64(108), np.int64(109), np.int64(110), np.int64(111), np.int64(112), np.int64(113), np.int64(114), np.int64(115), np.int64(116), np.int64(117), np.int64(118), np.int64(119), np.int64(120), np.int64(121), np.int64(122), np.int64(123), np.int64(124), np.int64(125), np.int64(126), np.int64(127), np.int64(128), np.int64(129), np.int64(130), np.int64(131), np.int64(132), np.int64(133), np.int64(134), np.int64(135), np.int64(137), np.int64(138), np.int64(139), np.int64(140), np.int64(141), np.int64(142), np.int64(143), np.int64(144), np.int64(145), np.int64(146), np.int64(147), np.int64(148), np.int64(149), np.int64(150), np.int64(151), np.int64(152), np.int64(153), np.int64(154), np.int64(155), np.int64(156), np.int64(157), np.int64(158), np.int64(159), np.int64(160), np.int64(161), np.int64(162), np.int64(163), np.int64(164), np.int64(165), np.int64(166), np.int64(167), np.int64(168), np.int64(169), np.int64(170), np.int64(171), np.int64(172), np.int64(3290), np.int64(174), np.int64(175), np.int64(176), np.int64(177), np.int64(178), np.int64(179), np.int64(180), np.int64(181), np.int64(182), np.int64(183), np.int64(184), np.int64(185), np.int64(186), np.int64(187), np.int64(188), np.int64(189), np.int64(190), np.int64(191), np.int64(192), np.int64(193), np.int64(194), np.int64(195), np.int64(196), np.int64(197), np.int64(199), np.int64(200), np.int64(201), np.int64(202), np.int64(203), np.int64(204), np.int64(205), np.int64(206), np.int64(207), np.int64(208), np.int64(209), np.int64(210), np.int64(211), np.int64(212), np.int64(213), np.int64(214), np.int64(215), np.int64(216), np.int64(217), np.int64(218), np.int64(219), np.int64(220), np.int64(221), np.int64(222), np.int64(223), np.int64(224), np.int64(225), np.int64(226), np.int64(227), np.int64(228), np.int64(229), np.int64(230), np.int64(231), np.int64(232), np.int64(233), np.int64(234), np.int64(235), np.int64(236), np.int64(237), np.int64(238), np.int64(239), np.int64(240), np.int64(241), np.int64(242), np.int64(243), np.int64(244), np.int64(245), np.int64(246), np.int64(247), np.int64(248), np.int64(249), np.int64(250), np.int64(251), np.int64(252), np.int64(253), np.int64(254), np.int64(255), np.int64(256), np.int64(257), np.int64(258), np.int64(259), np.int64(260), np.int64(261), np.int64(262), np.int64(263), np.int64(264), np.int64(265), np.int64(266), np.int64(267), np.int64(268), np.int64(269), np.int64(270), np.int64(271), np.int64(272), np.int64(273), np.int64(274), np.int64(275), np.int64(276), np.int64(277), np.int64(278), np.int64(279), np.int64(280), np.int64(281), np.int64(282), np.int64(283), np.int64(284), np.int64(285), np.int64(286), np.int64(287), np.int64(288), np.int64(289), np.int64(290), np.int64(291), np.int64(292), np.int64(293), np.int64(294), np.int64(295), np.int64(296), np.int64(297), np.int64(298), np.int64(299), np.int64(300), np.int64(301), np.int64(302), np.int64(303), np.int64(304), np.int64(305), np.int64(306), np.int64(307), np.int64(308), np.int64(309), np.int64(310), np.int64(311), np.int64(312), np.int64(313), np.int64(314), np.int64(315), np.int64(316), np.int64(317), np.int64(318), np.int64(319), np.int64(320), np.int64(321), np.int64(322), np.int64(323), np.int64(324), np.int64(325), np.int64(326), np.int64(327), np.int64(328), np.int64(329), np.int64(330), np.int64(331), np.int64(332), np.int64(333), np.int64(334), np.int64(335), np.int64(336), np.int64(337), np.int64(338), np.int64(339), np.int64(340), np.int64(341), np.int64(342), np.int64(343), np.int64(344), np.int64(345), np.int64(346), np.int64(347), np.int64(2704), np.int64(2740), np.int64(2814), np.int64(2838), np.int64(2885), np.int64(3003)], 'c1': [np.int64(2661), np.int64(2662), np.int64(2665), np.int64(2667), np.int64(2668), np.int64(2671), np.int64(2672), np.int64(2674), np.int64(2675), np.int64(2677), np.int64(2678), np.int64(2682), np.int64(2684), np.int64(2685), np.int64(2686), np.int64(2687), np.int64(2688), np.int64(2690), np.int64(2691), np.int64(2692), np.int64(2693), np.int64(2696), np.int64(2697), np.int64(2700), np.int64(2701), np.int64(2702), np.int64(2707), np.int64(2708), np.int64(2709), np.int64(2711), np.int64(2712), np.int64(2713), np.int64(2714), np.int64(2715), np.int64(2716), np.int64(2718), np.int64(2719), np.int64(2720), np.int64(2721), np.int64(2722), np.int64(2723), np.int64(2724), np.int64(2725), np.int64(2727), np.int64(2728), np.int64(2730), np.int64(2732), np.int64(2733), np.int64(2734), np.int64(2735), np.int64(2736), np.int64(2737), np.int64(2739), np.int64(2742), np.int64(2744), np.int64(2747), np.int64(2748), np.int64(2751), np.int64(2752), np.int64(2753), np.int64(2758), np.int64(2760), np.int64(2762), np.int64(2764), np.int64(2765), np.int64(2768), np.int64(2770), np.int64(2771), np.int64(2772), np.int64(2774), np.int64(2775), np.int64(2776), np.int64(2778), np.int64(2779), np.int64(2780), np.int64(2781), np.int64(2783), np.int64(2784), np.int64(2785), np.int64(2787), np.int64(2788), np.int64(2790), np.int64(2791), np.int64(2792), np.int64(2793), np.int64(2795), np.int64(2796), np.int64(2797), np.int64(2799), np.int64(2801), np.int64(2802), np.int64(2803), np.int64(2804), np.int64(2805), np.int64(2808), np.int64(2811), np.int64(2812), np.int64(2813), np.int64(2816), np.int64(2817), np.int64(2818), np.int64(2819), np.int64(2820), np.int64(2822), np.int64(2823), np.int64(2824), np.int64(2825), np.int64(2826), np.int64(2828), np.int64(2829), np.int64(2830), np.int64(2831), np.int64(2832), np.int64(2833), np.int64(2836), np.int64(2840), np.int64(2841), np.int64(2842), np.int64(2843), np.int64(2844), np.int64(2845), np.int64(2846), np.int64(2847), np.int64(2848), np.int64(2849), np.int64(2853), np.int64(2855), np.int64(2856), np.int64(2857), np.int64(2858), np.int64(2859), np.int64(2860), np.int64(2861), np.int64(2863), np.int64(2865), np.int64(2868), np.int64(2869), np.int64(2870), np.int64(2871), np.int64(2875), np.int64(2876), np.int64(2878), np.int64(2881), np.int64(2882), np.int64(2883), np.int64(2886), np.int64(2892), np.int64(2893), np.int64(2894), np.int64(2895), np.int64(2898), np.int64(2900), np.int64(2901), np.int64(2902), np.int64(2903), np.int64(2904), np.int64(2914), np.int64(2918), np.int64(2921), np.int64(2922), np.int64(2923), np.int64(2926), np.int64(2930), np.int64(2932), np.int64(2933), np.int64(2934), np.int64(2935), np.int64(2936), np.int64(2937), np.int64(2938), np.int64(2939), np.int64(2941), np.int64(2942), np.int64(2947), np.int64(2949), np.int64(2950), np.int64(2951), np.int64(2954), np.int64(2955), np.int64(2957), np.int64(2958), np.int64(2962), np.int64(2964), np.int64(2965), np.int64(2968), np.int64(2970), np.int64(2971), np.int64(2973), np.int64(2975), np.int64(2976), np.int64(2979), np.int64(2980), np.int64(2983), np.int64(2984), np.int64(2989), np.int64(2990), np.int64(2991), np.int64(2992), np.int64(2995), np.int64(2996), np.int64(2997), np.int64(2998), np.int64(2999), np.int64(3001), np.int64(3002), np.int64(3005), np.int64(3006), np.int64(3007), np.int64(3009), np.int64(3011), np.int64(3012), np.int64(3013), np.int64(3015), np.int64(3016), np.int64(3017), np.int64(3018), np.int64(3019), np.int64(3020), np.int64(3021), np.int64(3024), np.int64(3027), np.int64(3028), np.int64(3031), np.int64(3032), np.int64(3034), np.int64(3035), np.int64(3037), np.int64(3038), np.int64(3039), np.int64(990), np.int64(3041), np.int64(3043), np.int64(3046), np.int64(3048), np.int64(3049), np.int64(3050), np.int64(3051), np.int64(3053), np.int64(3055), np.int64(3057), np.int64(3058), np.int64(3060), np.int64(3061), np.int64(3062), np.int64(3063), np.int64(3066), np.int64(3067), np.int64(3068), np.int64(3069), np.int64(3070), np.int64(3071), np.int64(3072), np.int64(3074), np.int64(3075), np.int64(3076), np.int64(3077), np.int64(3079), np.int64(3081), np.int64(3082), np.int64(3083), np.int64(3086), np.int64(3087), np.int64(3088), np.int64(3089), np.int64(3091), np.int64(3093), np.int64(3094), np.int64(3097), np.int64(3099), np.int64(3100), np.int64(3101), np.int64(3102), np.int64(3103), np.int64(3105), np.int64(3106), np.int64(3107), np.int64(3109), np.int64(3110), np.int64(3111), np.int64(3112), np.int64(3113), np.int64(3115), np.int64(3116), np.int64(3118), np.int64(3120), np.int64(3121), np.int64(3122), np.int64(3124), np.int64(3125), np.int64(3126), np.int64(3127), np.int64(3128), np.int64(3131), np.int64(3132), np.int64(3133), np.int64(3134), np.int64(3136), np.int64(3138), np.int64(3140), np.int64(3141), np.int64(3144), np.int64(3145), np.int64(3146), np.int64(3147), np.int64(3148), np.int64(3150), np.int64(3151), np.int64(3152), np.int64(3154), np.int64(3155), np.int64(3156), np.int64(3157), np.int64(3159), np.int64(3160), np.int64(3161), np.int64(3162), np.int64(3164), np.int64(3165), np.int64(3167), np.int64(3168), np.int64(3169), np.int64(3170), np.int64(3171), np.int64(3172), np.int64(3173), np.int64(3175), np.int64(3176), np.int64(3177), np.int64(3178), np.int64(3179), np.int64(3180), np.int64(3181), np.int64(3182), np.int64(3183), np.int64(3185), np.int64(3186), np.int64(3187), np.int64(1140), np.int64(3188), np.int64(3189), np.int64(3190), np.int64(3192), np.int64(3191), np.int64(3194), np.int64(3196), np.int64(3197), np.int64(3198), np.int64(3199), np.int64(3200), np.int64(3201), np.int64(3203), np.int64(3204), np.int64(3205), np.int64(3206), np.int64(3207), np.int64(3208), np.int64(3209), np.int64(3210), np.int64(3211), np.int64(3212), np.int64(3214), np.int64(3215), np.int64(3216), np.int64(3217), np.int64(3218), np.int64(3219), np.int64(3221), np.int64(3222), np.int64(3223), np.int64(3224), np.int64(3225), np.int64(3230), np.int64(3233), np.int64(3235), np.int64(3236), np.int64(3239), np.int64(3240), np.int64(3241), np.int64(3242), np.int64(3244), np.int64(3245), np.int64(3246), np.int64(3247), np.int64(3248), np.int64(3249), np.int64(3251), np.int64(3252), np.int64(3253), np.int64(3254), np.int64(3255), np.int64(3256), np.int64(3258), np.int64(3259), np.int64(3260), np.int64(3261), np.int64(3262), np.int64(3263), np.int64(3264), np.int64(3265), np.int64(3266), np.int64(3267), np.int64(3268), np.int64(3270), np.int64(3271), np.int64(3272), np.int64(3273), np.int64(3274), np.int64(3275), np.int64(3276), np.int64(3277), np.int64(3278), np.int64(3279), np.int64(3280), np.int64(3281), np.int64(3282), np.int64(3285), np.int64(3287), np.int64(3288), np.int64(3289), np.int64(3291), np.int64(3292), np.int64(3295), np.int64(3296), np.int64(3297), np.int64(3298), np.int64(3299), np.int64(3302), np.int64(3305), np.int64(3306), np.int64(3307), np.int64(3308), np.int64(3310), np.int64(3312), np.int64(3313), np.int64(3316), np.int64(3319), np.int64(3320), np.int64(3321), np.int64(3322), np.int64(3323), np.int64(3326), np.int64(3327), np.int64(3328), np.int64(3329), np.int64(3330), np.int64(3331), np.int64(3332), np.int64(3334), np.int64(3335), np.int64(3336), np.int64(3337), np.int64(3338), np.int64(3340), np.int64(3341), np.int64(3342), np.int64(3343), np.int64(3344), np.int64(3345), np.int64(3346), np.int64(3347), np.int64(3349), np.int64(3350), np.int64(3351), np.int64(3352), np.int64(3353), np.int64(3354), np.int64(3355), np.int64(3356), np.int64(3357), np.int64(3358), np.int64(3359), np.int64(3360), np.int64(3361), np.int64(3365), np.int64(3366), np.int64(3367), np.int64(3368), np.int64(3369), np.int64(3370), np.int64(3371), np.int64(3372), np.int64(3373), np.int64(3374), np.int64(3375), np.int64(3376), np.int64(3377), np.int64(3378), np.int64(3379), np.int64(3380), np.int64(3381), np.int64(3383), np.int64(3385), np.int64(3386), np.int64(3389), np.int64(3391), np.int64(3393), np.int64(3395), np.int64(3396), np.int64(3397), np.int64(3398), np.int64(3401), np.int64(3402), np.int64(3403), np.int64(3404), np.int64(3405), np.int64(3406), np.int64(3407), np.int64(3408), np.int64(3409), np.int64(3410), np.int64(3411), np.int64(3412), np.int64(3415), np.int64(3416), np.int64(3418), np.int64(3419), np.int64(3420), np.int64(3421), np.int64(3422), np.int64(3424), np.int64(3425), np.int64(3427), np.int64(3429), np.int64(3431), np.int64(3432), np.int64(3434), np.int64(1450), np.int64(1505), np.int64(1534), np.int64(1642), np.int64(1656), np.int64(1666), np.int64(1684), np.int64(1726), np.int64(1758)], 'c2': [np.int64(1032), np.int64(1035), np.int64(1036), np.int64(1037), np.int64(1041), np.int64(1042), np.int64(1044), np.int64(1051), np.int64(1052), np.int64(1060), np.int64(1062), np.int64(1065), np.int64(1066), np.int64(1067), np.int64(1070), np.int64(1072), np.int64(1081), np.int64(1082), np.int64(1089), np.int64(1090), np.int64(1093), np.int64(1099), np.int64(1100), np.int64(1102), np.int64(1103), np.int64(1104), np.int64(1106), np.int64(1108), np.int64(1109), np.int64(1115), np.int64(1120), np.int64(1121), np.int64(1127), np.int64(1129), np.int64(1131), np.int64(1134), np.int64(1139), np.int64(1141), np.int64(1143), np.int64(1147), np.int64(1148), np.int64(1152), np.int64(1158), np.int64(1159), np.int64(1166), np.int64(1167), np.int64(1168), np.int64(1169), np.int64(1170), np.int64(1176), np.int64(1183), np.int64(1188), np.int64(1189), np.int64(1190), np.int64(1192), np.int64(1204), np.int64(1213), np.int64(1215), np.int64(1217), np.int64(1221), np.int64(1225), np.int64(1226), np.int64(1227), np.int64(1228), np.int64(1229), np.int64(1231), np.int64(1235), np.int64(1236), np.int64(1241), np.int64(1244), np.int64(1245), np.int64(1246), np.int64(1247), np.int64(1248), np.int64(1249), np.int64(1257), np.int64(1258), np.int64(1259), np.int64(1260), np.int64(1261), np.int64(1264), np.int64(1268), np.int64(1273), np.int64(1275), np.int64(1277), np.int64(1279), np.int64(1281), np.int64(1282), np.int64(1284), np.int64(1286), np.int64(1292), np.int64(1296), np.int64(1298), np.int64(1299), np.int64(1303), np.int64(1304), np.int64(1306), np.int64(1308), np.int64(1309), np.int64(1310), np.int64(1311), np.int64(1315), np.int64(1316), np.int64(1322), np.int64(1324), np.int64(1338), np.int64(1343), np.int64(1345), np.int64(1347), np.int64(1348), np.int64(1350), np.int64(1354), np.int64(1355), np.int64(1362), np.int64(1364), np.int64(1366), np.int64(1373), np.int64(1379), np.int64(1381), np.int64(1382), np.int64(1385), np.int64(1392), np.int64(1396), np.int64(1404), np.int64(1406), np.int64(1412), np.int64(1413), np.int64(1414), np.int64(389), np.int64(1415), np.int64(1417), np.int64(1418), np.int64(1423), np.int64(1426), np.int64(1428), np.int64(1429), np.int64(1432), np.int64(1435), np.int64(1436), np.int64(1438), np.int64(1444), np.int64(1448), np.int64(1451), np.int64(1454), np.int64(1459), np.int64(1462), np.int64(1469), np.int64(1472), np.int64(1473), np.int64(1474), np.int64(1475), np.int64(1479), np.int64(1481), np.int64(1482), np.int64(1489), np.int64(1492), np.int64(1495), np.int64(1496), np.int64(1500), np.int64(1502), np.int64(1503), np.int64(1504), np.int64(1507), np.int64(1508), np.int64(1510), np.int64(1515), np.int64(1525), np.int64(1529), np.int64(1531), np.int64(1536), np.int64(1541), np.int64(1550), np.int64(1569), np.int64(1573), np.int64(1575), np.int64(1576), np.int64(1578), np.int64(1582), np.int64(1583), np.int64(1587), np.int64(1591), np.int64(1592), np.int64(1595), np.int64(1596), np.int64(1611), np.int64(1624), np.int64(1628), np.int64(1630), np.int64(1633), np.int64(1634), np.int64(1635), np.int64(1636), np.int64(1638), np.int64(1640), np.int64(1646), np.int64(1647), np.int64(1649), np.int64(1650), np.int64(1655), np.int64(1658), np.int64(1661), np.int64(1664), np.int64(1667), np.int64(1672), np.int64(1680), np.int64(1681), np.int64(1682), np.int64(1686), np.int64(1690), np.int64(1691), np.int64(1699), np.int64(1703), np.int64(1704), np.int64(1706), np.int64(1709), np.int64(1713), np.int64(1715), np.int64(1716), np.int64(1720), np.int64(1725), np.int64(1727), np.int64(1728), np.int64(1729), np.int64(1732), np.int64(1738), np.int64(1739), np.int64(1742), np.int64(1745), np.int64(1748), np.int64(1749), np.int64(1751), np.int64(1755), np.int64(1756), np.int64(1759), np.int64(1764), np.int64(1770), np.int64(1781), np.int64(1783), np.int64(1785), np.int64(1786), np.int64(1794), np.int64(1807), np.int64(1812), np.int64(1815), np.int64(1818), np.int64(1820), np.int64(1824), np.int64(1828), np.int64(1830), np.int64(1840), np.int64(1841), np.int64(1847), np.int64(1848), np.int64(1850), np.int64(1855), np.int64(1857), np.int64(1859), np.int64(1862), np.int64(1869), np.int64(1871), np.int64(1872), np.int64(1873), np.int64(1875), np.int64(1876), np.int64(1884), np.int64(1885), np.int64(1887), np.int64(1893), np.int64(1894), np.int64(1897), np.int64(1899), np.int64(1903), np.int64(1904), np.int64(1906), np.int64(1907), np.int64(896), np.int64(898), np.int64(902), np.int64(913), np.int64(914), np.int64(917), np.int64(919), np.int64(924), np.int64(933), np.int64(935), np.int64(937), np.int64(940), np.int64(941), np.int64(942), np.int64(943), np.int64(944), np.int64(945), np.int64(949), np.int64(954), np.int64(957), np.int64(964), np.int64(965), np.int64(968), np.int64(969), np.int64(971), np.int64(974), np.int64(975), np.int64(977), np.int64(981), np.int64(984), np.int64(985), np.int64(986), np.int64(988), np.int64(989), np.int64(994), np.int64(1000), np.int64(1005), np.int64(1007), np.int64(1009), np.int64(1010), np.int64(1011), np.int64(1013), np.int64(1014), np.int64(1015), np.int64(1018), np.int64(1019), np.int64(1020), np.int64(1021)], 'c3': [np.int64(1798), np.int64(1030), np.int64(1033), np.int64(1546), np.int64(1802), np.int64(1548), np.int64(1803), np.int64(1806), np.int64(1553), np.int64(1043), np.int64(1555), np.int64(1045), np.int64(1562), np.int64(1307), np.int64(1053), np.int64(1567), np.int64(1568), np.int64(1057), np.int64(1314), np.int64(1825), np.int64(1061), np.int64(1319), np.int64(1579), np.int64(1837), np.int64(1325), np.int64(1328), np.int64(1073), np.int64(1588), np.int64(1333), np.int64(1593), np.int64(1601), np.int64(1607), np.int64(1097), np.int64(1353), np.int64(1866), np.int64(1098), np.int64(1615), np.int64(1360), np.int64(1363), np.int64(1111), np.int64(1880), np.int64(1368), np.int64(1371), np.int64(1629), np.int64(1118), np.int64(1889), np.int64(1378), np.int64(1892), np.int64(1895), np.int64(1896), np.int64(1384), np.int64(1648), np.int64(1137), np.int64(1138), np.int64(1136), np.int64(1394), np.int64(1908), np.int64(1144), np.int64(1403), np.int64(1410), np.int64(900), np.int64(901), np.int64(903), np.int64(1676), np.int64(909), np.int64(908), np.int64(1421), np.int64(1424), np.int64(1174), np.int64(1687), np.int64(1177)

In [7]:
from collections import defaultdict

In [22]:
local_part = {}

for node in G.nodes():
    deg = G.degree(node)
    if deg == 0:
        local_part[node] = 0
        continue

    edge_to_comm_count = defaultdict(int)
    for ngb in G.neighbors(node):
        edge_to_comm_count[node_coms[ngb]] += 1

In [29]:
intra = G.degree()

In [34]:
m = np.mean(list(intra))
m

np.float64(2019.0)

In [46]:
df = pd.read_csv('../data/local_roles.csv')
df

      Unnamed: 0  node community              local_role
0              0     0        c0  Local Ultra-Peripheral
1              1     1        c0  Local Ultra-Peripheral
2              2     2        c0  Local Ultra-Peripheral
3              3     3        c0  Local Ultra-Peripheral
4              4     4        c0  Local Ultra-Peripheral
...          ...   ...       ...                     ...
4034        4034  4034       c15  Local Ultra-Peripheral
4035        4035  4035       c15  Local Ultra-Peripheral
4036        4036  4036       c15  Local Ultra-Peripheral
4037        4037  4037       c15  Local Ultra-Peripheral
4038        4038  4038       c15  Local Ultra-Peripheral

[4039 rows x 4 columns]

In [61]:
node = 0
l_role = df.loc[0].at['node']
l_role

np.int64(0)

In [54]:
for row in df.itertuples():
    print(row)

Pandas(Index=0, _1=0, node=0, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=1, _1=1, node=1, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=2, _1=2, node=2, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=3, _1=3, node=3, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=4, _1=4, node=4, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=5, _1=5, node=5, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=6, _1=6, node=6, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=7, _1=7, node=7, community='c0', local_role='Local Peripheral')
Pandas(Index=8, _1=8, node=8, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=9, _1=9, node=9, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=10, _1=10, node=10, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=11, _1=11, node=11, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=12, _1=12, node=12, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=13, _1=13, node=13, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=14, _1=14, node=14, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=15, _1=15, node=15, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=16, _1=16, node=16, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=17, _1=17, node=17, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=18, _1=18, node=18, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=19, _1=19, node=19, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=20, _1=20, node=20, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=21, _1=21, node=21, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=22, _1=22, node=22, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=23, _1=23, node=23, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=24, _1=24, node=24, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=25, _1=25, node=25, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=26, _1=26, node=26, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=27, _1=27, node=27, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=28, _1=28, node=28, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=29, _1=29, node=29, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=30, _1=30, node=30, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=31, _1=31, node=31, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=32, _1=32, node=32, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=33, _1=33, node=33, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=34, _1=34, node=34, community='c4', local_role='Local Peripheral')
Pandas(Index=35, _1=35, node=35, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=36, _1=36, node=36, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=37, _1=37, node=37, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=38, _1=38, node=38, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=39, _1=39, node=39, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=40, _1=40, node=40, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=41, _1=41, node=41, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=42, _1=42, node=42, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=43, _1=43, node=43, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=44, _1=44, node=44, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=45, _1=45, node=45, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=46, _1=46, node=46, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=47, _1=47, node=47, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=48, _1=48, node=48, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=49, _1=49, node=49, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=50, _1=50, node=50, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=51, _1=51, node=51, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=52, _1=52, node=52, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=53, _1=53, node=53, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=54, _1=54, node=54, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=55, _1=55, node=55, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=56, _1=56, node=56, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=57, _1=57, node=57, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=58, _1=58, node=58, community='c0', local_role='Local Peripheral')
Pandas(Index=59, _1=59, node=59, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=60, _1=60, node=60, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=61, _1=61, node=61, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=62, _1=62, node=62, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=63, _1=63, node=63, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=64, _1=64, node=64, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=65, _1=65, node=65, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=66, _1=66, node=66, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=67, _1=67, node=67, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=68, _1=68, node=68, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=69, _1=69, node=69, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=70, _1=70, node=70, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=71, _1=71, node=71, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=72, _1=72, node=72, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=73, _1=73, node=73, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=74, _1=74, node=74, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=75, _1=75, node=75, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=76, _1=76, node=76, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=77, _1=77, node=77, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=78, _1=78, node=78, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=79, _1=79, node=79, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=80, _1=80, node=80, community='c0', local_role='Local Peripheral')
Pandas(Index=81, _1=81, node=81, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=82, _1=82, node=82, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=83, _1=83, node=83, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=84, _1=84, node=84, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=85, _1=85, node=85, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=86, _1=86, node=86, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=87, _1=87, node=87, community='c0', local_role='Local Peripheral')
Pandas(Index=88, _1=88, node=88, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=89, _1=89, node=89, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=90, _1=90, node=90, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=91, _1=91, node=91, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=92, _1=92, node=92, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=93, _1=93, node=93, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=94, _1=94, node=94, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=95, _1=95, node=95, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=96, _1=96, node=96, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=97, _1=97, node=97, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=98, _1=98, node=98, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=99, _1=99, node=99, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=100, _1=100, node=100, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=101, _1=101, node=101, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=102, _1=102, node=102, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=103, _1=103, node=103, community='c0', local_role='Local Peripheral')
Pandas(Index=104, _1=104, node=104, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=105, _1=105, node=105, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=106, _1=106, node=106, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=107, _1=107, node=107, community='c2', local_role='Local Connector')
Pandas(Index=108, _1=108, node=108, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=109, _1=109, node=109, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=110, _1=110, node=110, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=111, _1=111, node=111, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=112, _1=112, node=112, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=113, _1=113, node=113, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=114, _1=114, node=114, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=115, _1=115, node=115, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=116, _1=116, node=116, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=117, _1=117, node=117, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=118, _1=118, node=118, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=119, _1=119, node=119, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=120, _1=120, node=120, community='c0', local_role='Local Peripheral')
Pandas(Index=121, _1=121, node=121, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=122, _1=122, node=122, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=123, _1=123, node=123, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=124, _1=124, node=124, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=125, _1=125, node=125, community='c0', local_role='Local Peripheral')
Pandas(Index=126, _1=126, node=126, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=127, _1=127, node=127, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=128, _1=128, node=128, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=129, _1=129, node=129, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=130, _1=130, node=130, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=131, _1=131, node=131, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=132, _1=132, node=132, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=133, _1=133, node=133, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=134, _1=134, node=134, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=135, _1=135, node=135, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=136, _1=136, node=136, community='c13', local_role='Local Peripheral')
Pandas(Index=137, _1=137, node=137, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=138, _1=138, node=138, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=139, _1=139, node=139, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=140, _1=140, node=140, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=141, _1=141, node=141, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=142, _1=142, node=142, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=143, _1=143, node=143, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=144, _1=144, node=144, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=145, _1=145, node=145, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=146, _1=146, node=146, community='c0', local_role='Local Peripheral')
Pandas(Index=147, _1=147, node=147, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=148, _1=148, node=148, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=149, _1=149, node=149, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=150, _1=150, node=150, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=151, _1=151, node=151, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=152, _1=152, node=152, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=153, _1=153, node=153, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=154, _1=154, node=154, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=155, _1=155, node=155, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=156, _1=156, node=156, community='c0', local_role='Local Peripheral')
Pandas(Index=157, _1=157, node=157, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=158, _1=158, node=158, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=159, _1=159, node=159, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=160, _1=160, node=160, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=161, _1=161, node=161, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=162, _1=162, node=162, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=163, _1=163, node=163, community='c0', local_role='Local Peripheral')
Pandas(Index=164, _1=164, node=164, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=165, _1=165, node=165, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=166, _1=166, node=166, community='c0', local_role='Local Peripheral')
Pandas(Index=167, _1=167, node=167, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=168, _1=168, node=168, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=169, _1=169, node=169, community='c0', local_role='Local Peripheral')
Pandas(Index=170, _1=170, node=170, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=171, _1=171, node=171, community='c0', local_role='Local Peripheral')
Pandas(Index=172, _1=172, node=172, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=173, _1=173, node=173, community='c4', local_role='Local Peripheral')
Pandas(Index=174, _1=174, node=174, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=175, _1=175, node=175, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=176, _1=176, node=176, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=177, _1=177, node=177, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=178, _1=178, node=178, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=179, _1=179, node=179, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=180, _1=180, node=180, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=181, _1=181, node=181, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=182, _1=182, node=182, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=183, _1=183, node=183, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=184, _1=184, node=184, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=185, _1=185, node=185, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=186, _1=186, node=186, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=187, _1=187, node=187, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=188, _1=188, node=188, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=189, _1=189, node=189, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=190, _1=190, node=190, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=191, _1=191, node=191, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=192, _1=192, node=192, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=193, _1=193, node=193, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=194, _1=194, node=194, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=195, _1=195, node=195, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=196, _1=196, node=196, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=197, _1=197, node=197, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=198, _1=198, node=198, community='c4', local_role='Local Peripheral')
Pandas(Index=199, _1=199, node=199, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=200, _1=200, node=200, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=201, _1=201, node=201, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=202, _1=202, node=202, community='c0', local_role='Local Peripheral')
Pandas(Index=203, _1=203, node=203, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=204, _1=204, node=204, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=205, _1=205, node=205, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=206, _1=206, node=206, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=207, _1=207, node=207, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=208, _1=208, node=208, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=209, _1=209, node=209, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=210, _1=210, node=210, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=211, _1=211, node=211, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=212, _1=212, node=212, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=213, _1=213, node=213, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=214, _1=214, node=214, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=215, _1=215, node=215, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=216, _1=216, node=216, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=217, _1=217, node=217, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=218, _1=218, node=218, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=219, _1=219, node=219, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=220, _1=220, node=220, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=221, _1=221, node=221, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=222, _1=222, node=222, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=223, _1=223, node=223, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=224, _1=224, node=224, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=225, _1=225, node=225, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=226, _1=226, node=226, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=227, _1=227, node=227, community='c0', local_role='Local Ultra-Peripheral')
Pandas(Index=228, _1=228, node=228, community='c0', local_role='Local Ultra-Peripheral')